### ISSUE TITLE
Spike: wasm interpreters

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/casper-node#2221]

**Comment by mpapierski** [comment]
After some investigation, we went with https://github.com/bytecodealliance/wasmtime for executing WASM. The other alternative considered was `wasmer` which has an excellent single-pass compiler. Still, we rejected that due to rigorous requirements on types used in the env requiring us to do a possibly significant refactor in our code.

The last question I wanted to answer before proceeding was testing already stored WASMs pre-wasmtime migration and their compatibility with gas accounting. We do store wasms with gas counters injected already. It is possible, although I've encountered a strangeness around import/export of `memory` extern, which I resolved. This change is also compatible in a future where we've changed the notion of gas, and we can hook up the "gas" function (if it's imported from a pre-wasmtime contract) into the fuel API rather than advancing a gas counter.

In our benchmarks, wasmtime showed excellent results:

```
tps/transfer_to_existing_account_multiple_execs/3/false                                                                             
                        time:   [1.9752 ms 2.0011 ms 2.0166 ms] 
                        thrpt:  [1.4877 Kelem/s 1.4992 Kelem/s 1.5189 Kelem/s] 
                 change: 
                        time:   [-48.058% -47.515% -46.989%] (p = 0.00 < 0.05) 
                        thrpt:  [+88.641% +90.529% +92.524%] 
                        Performance has improved. 
tps/transfer_to_existing_account_multiple_deploys_per_exec/3/false                                                                             
                        time:   [1.9193 ms 1.9361 ms 1.9511 ms] 
                        thrpt:  [1.5376 Kelem/s 1.5495 Kelem/s 1.5631 Kelem/s] 
                 change: 
                        time:   [-43.340% -43.032% -42.691%] (p = 0.00 < 0.05) 
                        thrpt:  [+74.493% +75.538% +76.492%] 
                        Performance has improved. 
tps/transfer_to_existing_account_multiple_execs/3/true                                                                             
                        time:   [3.0053 ms 3.0446 ms 3.0675 ms] 
                        thrpt:  [978.00  elem/s 985.36  elem/s 998.24  elem/s] 
                 change: 
                        time:   [-38.663% -37.869% -36.999%] (p = 0.00 < 0.05) 
                        thrpt:  [+58.727% +60.951% +63.034%] 
                        Performance has improved. 
tps/transfer_to_existing_account_multiple_deploys_per_exec/3/true                                                                             
                        time:   [2.1495 ms 2.1615 ms 2.1688 ms] 
                        thrpt:  [1.3833 Kelem/s 1.3879 Kelem/s 1.3957 Kelem/s] 
                 change: 
                        time:   [-41.943% -41.455% -40.985%] (p = 0.00 < 0.05) 
                        thrpt:  [+69.450% +70.809% +72.246%] 
                        Performance has improved.
```

Additionally, one of our pessimistic tests (`endless_loop.wasm`) now runs below 1 second, where interpreted mode runs in 60 seconds or more.

Worth noting that we're trying to pursue ahead of time mode, which has slight overhead in precompilation times. On average, simple deploys (i.e., do minimum) are about ~5ms slower to execute, but larger non-trivial ones are getting faster quickly (i.e., endless_loop).
